name: app-share-gps-trace
author: gerald reinhart
description: Sharing gps trace files
dependencies:
  browser: any
  mongo_dart: any
  unittest: any
  stream: ">= 0.8.7" 
  rikulo_security: any
  crypto: any
  bootjack: any
  xml: any
  js: any 
