name: app_share_gps_trace
author: gerald reinhart
description: Sharing gps trace files
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  bootjack: any
  browser: any
  crypto: any
  js: any
  mongo_dart: any
  rikulo_security: any
  stream: '>= 0.8.7'
  xml: any
dev_dependencies:
  unittest: any
 