name: dart_trails
author: gerald reinhart
description: Sharing gps trace files
dependencies:
  browser: any
  mongo_dart: any
  unittest: any
  stream: any
  rikulo_security: any
  crypto: any
  bootjack: any
  xml: any