name: app_share_gps_trace
author: gerald reinhart
description: Sharing gps trace files
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  bootjack: "0.6.1+7"
  dquery: "0.5.3+5"
  browser: "0.9.0"
  crypto: "0.9.0"
  js: "0.2.0"
  mongo_dart: "0.1.35"
  rikulo_security: "0.6.1"
  stream: '1.0.0'
  petitparser: '1.0.0'
  http_server: "0.9.0"
  intl: "0.9.1"
  unittest: "0.9.0"
 
