name: app_share_gps_trace
author: gerald reinhart
description: Sharing gps trace files
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  bootjack: any
  browser: any
  crypto: any
  js: any
  mongo_dart: any
  rikulo_security: 
    git: git://github.com/rikulo/security.git
  stream: '1.0.0'
  petitparser: '1.0.0'
  http_server: any
  intl: any
  unittest: any
 