//Auto-generated by RSP Compiler
//Source: aboutAuthorFragment.rsp.html
part of trails;

/** Template, aboutAuthorFragment, for rendering the view. */
Future aboutAuthorFragment(HttpConnect connect) { //#2
  var _t0_, _cs_ = new List<HttpConnect>();
  HttpRequest request = connect.request;
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return new Future.value();

  response.write("""

           <h2>Auteur</h2>
           
           <p>Grenoble est le paradis du randonneur de moyenne montagne et du ski de randonnée. J'ai pris le virus : aller me balader
            en Charteuse, Vercors ou Belledonne est toujours un vrai plaisir, un vrai dépaysement. L'hiver, comme tout Grenoblois, j'attends 
            avec impatience les premiers flocons pour sortir les peaux de phoques et aller faire les premières conversions. Plus 
            récemment je me suis mis au trail, ma participation à l'UT4M en relais cette année m'a vraiment donné envie de découvrir
             nos montagnes en courant. Enfin, au cours de mes différents voyages j'ai également eu l'occasion de faire de merveilleux
              treks en Alaska, Yukon, Guatémala, La Réunion ou encore en Bolivie.</p>

          <p>Dans toutes ces activités, un outil indispensable est bien entendu la boussole, ou bien sûr sa version moderne qu'est le gps.</p>
 
          <p>Côté vie professionnelle, je suis ingénieur de développement logiciel depuis 2001. Pendant tout ce temps passé à développer 
            des outils pour les autres, je me disais que ce serait bien, un jour, de prendre du temps pour développer une application web 
            de A à Z avec comme seules contraintes celles que je me poserais. Passionné de nouvelles technologies, je récemment découvert
             un langage émergeant accompagné de son environnement de développement pour le web : <a href="https://www.dartlang.org/" target="_blank" >Dart</a> porté par Google.</p>

   <p>Tous les éléments ont donc été réunis pour que je me lance :</p>
       <ul>
         <li>le quoi : une bonne idée de projet : une application web de partage de données gps.</li>
         <li>le comment : la plateforme <a href="https://www.dartlang.org/" target="_blank" >Dart</a> ainsi que de nombreux services disponibles sur le web facilitant le développement, l'intégration continue et l'exploitation en production (<a href="https://github.com/GeReinhart/app-share-gps-trace" target="_blank" >GitHub</a>, <a href="https://trello.com/b/OsBs3WpR/la-boussole-backlog" target="_blank" >Trello</a>, <a href="https://drone.io/github.com/GeReinhart/app-share-gps-trace" target="_blank" >Drone</a>, <a href="https://www.heroku.com/" target="_blank" >Heroku</a>, <a href="https://www.mongolab.com" target="_blank" >MongoLab</a>).</li>
         <li>le pourquoi : me prouver que j'en suis capable tout simplement, me constituer une formidable carte visite et enfin et surtout créer application utile.</li>
       </ul>
   
   <p>Le 18/12/2013,             Gérald Reinhart </p>

   <p><a href="http://www.linkedin.com/pub/gerald-reinhart/15/a30/10" target="_blank" >Profil LinkedIn</a></p>
   <p>Mail : gerald <span style="font-style: italic; " >dot</span> reinhart <span style="font-style: italic; " >at</span> gmail <span style="font-style: italic; " >dot</span> com</p>
   <p>&nbsp;</p>
   <p>&nbsp;</p>  
"""); //#2

  return new Future.value();
}
