//Auto-generated by RSP Compiler
//Source: aboutDevFragment.rsp.html
part of trails;

/** Template, aboutDevFragment, for rendering the view. */
Future aboutDevFragment(HttpConnect connect) { //#2
  var _t0_, _cs_ = new List<HttpConnect>();
  HttpRequest request = connect.request;
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return new Future.value();

  response.write("""

           <h2>Derriere la scène</h2>
           <div class="text-warning  form-error-message" >En construction : texte présentant les enjeux techniques de construction et d'évolution de l'application.</div>

"""); //#2

  return new Future.value();
}
