//Auto-generated by RSP Compiler
//Source: aboutFeedbacksFragment.rsp.html
part of trails;

/** Template, aboutFeedbacksFragment, for rendering the view. */
Future aboutFeedbacksFragment(HttpConnect connect) { //#2
  var _t0_, _cs_ = new List<HttpConnect>();
  HttpRequest request = connect.request;
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return new Future.value();

  response.write("""

           <h2>Retour</h2>
           <div class="text-warning  form-error-message" >En construction : permettre aux utilisateurs de remonter des bugs ou de proposer des améliorations.</div>
"""); //#2

  return new Future.value();
}
