//Auto-generated by RSP Compiler
//Source: indexButtonsFragment.rsp.html
part of trails;

/** Template, indexButtonsFragment, for rendering the view. */
Future indexButtonsFragment(HttpConnect connect) { //#2
  var _t0_, _cs_ = new List<HttpConnect>();
  HttpRequest request = connect.request;
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return new Future.value();

  response.write("""        <div class="form-group">
           <div id="index-btn-when-anonymous" """); //#2

  if (currentUser(request.session) != null) { //if#3

    response.write("""class="gx-hidden\""""); //#3
  } //if

  response.write(""" >
              <button  type="submit" class="btn btn-primary btn-login">Se connecter</button>&nbsp;
              <button  type="submit" class="btn btn-default btn-register">S'enregister</button>&nbsp;
              <button  type="submit" class="btn btn-warning btn-search loading-on-click">Rechercher une trace</button>
           </div>
           <div id="index-btn-when-logged" """); //#3

  if (currentUser(request.session) == null) { //if#8

    response.write("""class="gx-hidden\""""); //#8
  } //if

  response.write("""  >
             <button  type="submit" class="btn btn-primary btn-add">Ajouter une trace</button>&nbsp;
             <button  type="submit" class="btn btn-warning btn-search loading-on-click">Rechercher une trace</button>
           </div>
        </div>
        <div style="margin-top: 20px"  class="text-warning  form-error-message" >Cette application est actuellement en construction.</div>
"""); //#8

  return new Future.value();
}
