//Auto-generated by RSP Compiler
//Source: legalDisclaimerFragment.rsp.html
part of trails;

/** Template, legalDisclaimerFragment, for rendering the view. */
Future legalDisclaimerFragment(HttpConnect connect) { //#2
  var _t0_, _cs_ = new List<HttpConnect>();
  HttpRequest request = connect.request;
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return new Future.value();

  response.write("""

<h2>Mentions légales</h2>

  <p>la-boussole.info est un site web réalisé, maintenu et représenté par Gérald Reinhart en tant que particulier :
    <ul>
      <li>Gérald Reinhart</li>
      <li>8 place Valmy</li>
      <li>38130 Echirolles, France</li>
      <li>mail: gerald [point] reinhart [at] gmail [point] com</li>
    </ul>
  </p>
  <p>Ce site est hébergé par <a href="https://www.heroku.com/contact" target="_blank" >Heroku</a> :
    <ul>
      <li>Heroku, Inc.</li>
      <li>650 7th Street</li>
      <li>San Francisco, CA, USA</li>
    </ul>
  </p>
  <p>Conformément à la loi "Informatique et Libertés" du 6 janvier 1978, modifiée par la loi du 6 août 2004, la dispense n°6 indique que les particuliers à titre privé sont dispensé de déclaration :
        </p>
        <p class="gx-text-quote"><a href="http://www.cnil.fr/vos-obligations/declarer-a-la-cnil/dispense/mon-secteur-dactivite/mon-theme/mon-fichier/dispense-selectionnee/dec-mode/DISPLAYSINGLEFICHEDISP/dis-uid/38/?tx_oxcscnildeclaration_pi1[sauid]=0&tx_oxcscnildeclaration_pi1[tuid]=0&cHash=c3a74d11e8a0a37723657455eb47d703" target="_blank" >Résumé</a>: La dispense n°6 concerne les sites web ou blogs mis en œuvre par des particuliers à titre privé qui peuvent permettre, d’une part, la collecte de données à caractère personnel de personnes qui s’y connectent et, d’autre part, la diffusion de données à caractère personnel (nom, images de personnes ou tout autre élément permettant d’identifier une personne physique).
        </p>
        <p class="gx-text-quote">La diffusion et la collecte de données à caractère personnel opérées à partir d’un site web dans le cadre d’activités professionnelles, politiques, ou associatives restent soumises à une déclaration préalable auprès de la CNIL.
        </p>
  <p><a target="_blank" href="http://www.legifrance.gouv.fr/jopdf/common/jo_pdf.jsp?numJO=0&dateJO=20051217&numTexte=79&pageDebut=&pageFin=">CF texte complet de la dispense n°6</a>
  </p>


  <p>Dernière mise à jour : 31 janvier 2014</p>
"""); //#2

  return new Future.value();
}
