//Auto-generated by RSP Compiler
//Source: traceDisplayMapFragment.rsp.html
part of trails;

/** Template, traceDisplayMapFragment, for rendering the view. */
Future traceDisplayMapFragment(HttpConnect connect, {traceRenderer}) { //#2
  var _t0_, _cs_ = new List<HttpConnect>();
  HttpRequest request = connect.request;
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return new Future.value();

  return Rsp.nnf(traceGpxViewer(new HttpConnect.chain(connect), traceRenderer: traceRenderer)).then((_) { //include#2

    return new Future.value();
  }); //end-of-include
}
