//Auto-generated by RSP Compiler
//Source: traceSearchMapFragment.rsp.html
part of trails;

/** Template, traceSearchMapFragment, for rendering the view. */
Future traceSearchMapFragment(HttpConnect connect, {lightTraceRenderers}) { //#2
  var _t0_, _cs_ = new List<HttpConnect>();
  HttpRequest request = connect.request;
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return new Future.value();

  return Rsp.nnf(searchResultsOnMap(new HttpConnect.chain(connect), lightTraceRenderers: lightTraceRenderers)).then((_) { //include#2

    return new Future.value();
  }); //end-of-include
}
