//Auto-generated by RSP Compiler
//Source: traceFormSubmitFragment.rsp.html
part of trails;

/** Template, traceFormSubmitFragment, for rendering the view. */
Future traceFormSubmitFragment(HttpConnect connect) { //#2
  var _t0_, _cs_ = new List<HttpConnect>();
  HttpRequest request = connect.request;
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return new Future.value();

  response.write("""          <table class="table-form" style="width: 100% ; ">
          <tr style="height: 40px">
             <td style="width: 10%;"  ></td>
             <td colspan="2" style="width: * ; text-align: center;"  >
                <div id="trace-form-error-message" class="text-warning gx-hidden" style="text-align: center;"  ></div>
             </td>
             <td style="width: 10%;"  ></td>
          </tr> 
          <tr>
             <td style="width: 10%;"  ></td>
             <td colspan="2" style="width: * ;   >
                <div class="form-inputs" style="text-align: center;" >
                 <button id="trace-form-submit" class="btn btn-primary">Ajouter cette trace</button>
                </div> 
             </td>
             <td style="width: 10%;"  ></td>
          </tr>    
          <tr style="height: 20px"><td colspan="4" /></tr>
          <tr >
             <td style="width: 10%;"  ></td>
             <td colspan="2" style="width: * ;   >
                <div id="trace-form-update-message"  class="alert alert-info">Possibilité d'ajouter des marqueurs sur la carte par un simple click droit.</div>
             </td>
             <td style="width: 10%;"  ></td>
          </tr>                                       
          </table>


              

"""); //#2

  return new Future.value();
}
