//Auto-generated by RSP Compiler
//Source: traceSearchFormFragment.rsp.html
part of trails;

/** Template, traceSearchFormFragment, for rendering the view. */
Future traceSearchFormFragment(HttpConnect connect, {traceFormRenderer}) { //#2
  var _t0_, _cs_ = new List<HttpConnect>();
  HttpRequest request = connect.request;
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return new Future.value();

  response.write("""        <h1>Rechercher une trace gps</h1>
"""); //#2

  return Rsp.nnf(searchForm(new HttpConnect.chain(connect), traceFormRenderer: traceFormRenderer)).then((_) { //include#3

    return new Future.value();
  }); //end-of-include
}
