//Auto-generated by RSP Compiler
//Source: traceDisplayCommentsFragment.rsp.html
part of trails;

/** Template, traceDisplayCommentsFragment, for rendering the view. */
Future traceDisplayCommentsFragment(HttpConnect connect) { //#2
  var _t0_, _cs_ = new List<HttpConnect>();
  HttpRequest request = connect.request;
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return new Future.value();

  response.write("""

           <div class="text-warning  form-error-message" style="margin-top: 20px"  >En construction : commentaires, photos, note.</div>


"""); //#2

  return new Future.value();
}
