//Auto-generated by RSP Compiler
//Source: traceDisplayMapFragment.rsp.html
part of trails;

/** Template, traceDisplayMapFragment, for rendering the view. */
Future traceDisplayMapFragment(HttpConnect connect) { //#2
  var _t0_, _cs_ = new List<HttpConnect>();
  HttpRequest request = connect.request;
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return new Future.value();

  response.write("""

    <div id="trace-details-map-canvas"></div>
    <script type="text/javascript">
        var traceDetailsMap = new GxMap("trace-details-map-canvas","gnst6zrvh2tnhhulo1kovnh1", new GxIconBuilder() ).init();
    </script>
"""); //#2

  return new Future.value();
}
