//Auto-generated by RSP Compiler
//Source: loading.rsp.html
part of trails;

/** Template, loading, for rendering the view. */
Future loading(HttpConnect connect) { //#2
  var _t0_, _cs_ = new List<HttpConnect>();
  HttpRequest request = connect.request;
  HttpResponse response = connect.response;
  Rsp.init(connect, "text/html; charset=utf-8");

  response.write("""<div class="space-loading" ><a href="#"><img  height="180px" width="180px" src="assets/img/spinner.gif"></img></a></div>
"""); //#2

  return Rsp.nnf();
}
