//Auto-generated by RSP Compiler
//Source: menu.rsp.html
part of trails;

/** Template, menu, for rendering the view. */
Future menu(HttpConnect connect) { //#2
  var _t0_, _cs_ = new List<HttpConnect>();
  HttpRequest request = connect.request;
  HttpResponse response = connect.response;
  Rsp.init(connect, "text/html; charset=utf-8");

  response.write("""    <div class="space-menu"  >
        <ul role="menu" class="dropdown-menu open" id="menu">
          <li role="presentation" class="dropdown-header">A propos</li>
          <li role="presentation"><a href="/mock" tabindex="-1" role="menuitem">Maquette</a></li>
          <li class="divider" role="presentation"></li>
          <li role="presentation" class="dropdown-header">Compte """); //#2

  response.write(Rsp.nnx(currentUser(request.session) != null ? "de " + currentUser(request.session).login: "")); //#7


  response.write("""</li>
"""); //#7

  if (currentUser(request.session) != null) { //if#8

    response.write("""            <li role="presentation"><a href="/logout" tabindex="-1" role="menuitem">Se déconnecter</a></li>
"""); //#9

  } else { //else#10

    response.write("""            <li role="presentation"><a href="/login" tabindex="-1" role="menuitem">Se connecter</a></li>
            <li role="presentation"><a href="/register" tabindex="-1" role="menuitem">S'enregistrer</a></li>
"""); //#11
  } //if

  response.write("""

        </ul>
    </div>"""); //#14

  return Rsp.nnf();
}
