//Auto-generated by RSP Compiler
//Source: persistentMenu.rsp.html
part of trails;

/** Template, persistentMenu, for rendering the view. */
Future persistentMenu(HttpConnect connect) { //#2
  var _t0_, _cs_ = new List<HttpConnect>();
  HttpRequest request = connect.request;
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return new Future.value();

  response.write("""<div class="space-persitent-menu" >
  <span class="inverse-video-display" >utilisateur """); //#2

  response.write(Rsp.nnx(currentUser(request.session) != null ?  currentUser(request.session).login: "anonyme")); //#3


  response.write("""</span>
  <span  ><a class="loading-on-click" href="/about"  >À propos</a></span>
  <span class="inverse-video-display" ><a class="loading-on-click" href="/disclaimer"  >Mentions légales</a></span>

</div>
"""); //#3

  return new Future.value();
}
