//Auto-generated by RSP Compiler
//Source: searchResults.rsp.html
part of trails;

/** Template, searchResults, for rendering the view. */
Future searchResults(HttpConnect connect, {lightTraceRenderers}) { //#2
  var _t0_, _cs_ = new List<HttpConnect>();
  HttpRequest request = connect.request;
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return new Future.value();

  response.write("""

        <table class="table table-striped" style="width: 100% ;margin-top: 40px">  
          <thead>  
            <tr>  
              <th style="width: 10%" >Auteur</th>  
              <th style="width: *" >Trace</th>  
              <th style="width: 15%" >Activités</th>  
              <th style="width: 10%" >Distance</th>  
              <th style="width: 10%" >Dénivelé</th>
              <th style="width: 10%" >Sommet</th>
              <th style="width: 10%" >Pente</th>
              <th style="width: 10%" >Difficulté</th>
            </tr>  
          </thead>  
          <tbody id="search-result-body" >  
             <tr id="search-result-row"  >
                  <td></td>  
                  <td></td>  
                  <td></td>
                  <td></td>  
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
             </tr>
"""); //#2

  for (var lightTraceRenderer in lightTraceRenderers) { //for#27

    response.write("""              <tr class="search-default-results" >  
                  <td>"""); //#28

    response.write(Rsp.nnx(lightTraceRenderer.creator)); //#29


    response.write("""</td>  
                  <td>"""); //#29

    response.write(Rsp.nnx(lightTraceRenderer.titleWithUrl, encode: 'none')); //#30


    response.write("""</td>  
                  <td>"""); //#30

    response.write(Rsp.nnx(lightTraceRenderer.activities)); //#31


    response.write("""</td>
                  <td>"""); //#31

    response.write(Rsp.nnx(lightTraceRenderer.length)); //#32


    response.write("""</td>  
                  <td>"""); //#32

    response.write(Rsp.nnx(lightTraceRenderer.up)); //#33


    response.write("""</td>
                  <td>"""); //#33

    response.write(Rsp.nnx(lightTraceRenderer.upperPointElevetion)); //#34


    response.write("""</td>
                  <td>"""); //#34

    response.write(Rsp.nnx(lightTraceRenderer.inclinationUp)); //#35


    response.write("""</td>
                  <td>"""); //#35

    response.write(Rsp.nnx(lightTraceRenderer.difficulty)); //#36


    response.write("""</td>
              </tr>  
"""); //#36
  } //for

  response.write("""    
          </tbody>  
        </table>
"""); //#39

  return new Future.value();
}
