//Auto-generated by RSP Compiler
//Source: searchResultsOnMap.rsp.html
part of trails;

/** Template, searchResultsOnMap, for rendering the view. */
Future searchResultsOnMap(HttpConnect connect, {lightTraceRenderers}) { //#2
  var _t0_, _cs_ = new List<HttpConnect>();
  HttpRequest request = connect.request;
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return new Future.value();

  response.write("""

    <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyACqUcoVGLVERGKxv09yqg9jv1iykUDJjA&sensor=false">
    </script>
    <script type="text/javascript">

      var map = null ;
      var markers = {};
      
      function addMarker(targetMap,  key,  title, lat, long ){
        if(key in markers){
          markers[key].setMap(map) ;
        }else{
          markers[key] = new google.maps.Marker({
            position:   new google.maps.LatLng(lat,long),
            map: targetMap,
            title: title
          });
        }
      }

      function addMarkerToMap( key,  title, lat, long ){
        addMarker(map,  key,  title, lat, long ) ;
      }      
      
      function removeMarker(key){
        if(key in markers){
          markers[key].setMap(null) ;
        }
      }

      function removeAllMarkers(){
        for (var key in markers) {
          markers[key].setMap(null);
        }
      }
      
      function initialize() {

        var baryCenter = new google.maps.LatLng("""); //#2

  response.write(Rsp.nnx(lightTraceRenderers.baryCenter.latitude)); //#41


  response.write(""",
                                                 """); //#41

  response.write(Rsp.nnx(lightTraceRenderers.baryCenter.longitude)); //#42


  response.write(""");
        
        var mapOptions = { zoom: 9,
                           mapTypeControl: false,
                           zoomControl: false,
                           center: baryCenter};
        
        map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
        
"""); //#42

  for (var lightTraceRenderer in lightTraceRenderers.traces) { //for#51

    response.write("""        addMarker(map,
                  \""""); //#52

    response.write(Rsp.nnx(lightTraceRenderer.keyJsSafe)); //#53


    response.write("""", 
                  \""""); //#53

    response.write(Rsp.nnx(lightTraceRenderer.titleJsSafe)); //#54


    response.write("""",
                  """); //#54

    response.write(Rsp.nnx(lightTraceRenderer.trace.startPointLatitude)); //#55


    response.write(""",
                  """); //#55

    response.write(Rsp.nnx(lightTraceRenderer.trace.startPointLongitude)); //#56


    response.write(""" ) ;
"""); //#56
  } //for

  response.write("""      
      }
      
      google.maps.event.addDomListener(window, 'load', initialize);
      
    </script>
    <div id="map-canvas"  class="space" ></div>

    

"""); //#58

  return new Future.value();
}
