//Auto-generated by RSP Compiler
//Source: spaces.rsp.html
part of trails;

/** Template, spaces, for rendering the view. */
Future spaces(HttpConnect connect, {w, nw, ne, sw, se}) { //#2
  var _t0_, _cs_ = new List<HttpConnect>();
  HttpRequest request = connect.request;
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return new Future.value();

  response.write("""<div class="space-loading">
    <img  height="180px" width="180px" src="/assets/img/spinner.gif"></img>
</div>
<div class="spaces" >
    <div class="space space-west"  > 
      <div class="inner-space" >
          """); //#2

  response.write(Rsp.nnx(w, encode: 'none')); //#8


  response.write("""

       </div>
    </div>
 	<div class="space space-north-west"  > 
	  <div class="inner-space" >
        """); //#8

  response.write(Rsp.nnx(nw, encode: 'none')); //#13


  response.write("""

  	  </div>
	</div>
	<div class="space space-north-east"  >
	  <div class="inner-space" >
        """); //#13

  response.write(Rsp.nnx(ne, encode: 'none')); //#18


  response.write("""

  	  </div>
    </div>
	<div class="space space-south-west"  > 
	  <div class="inner-space" >
        """); //#18

  response.write(Rsp.nnx(sw, encode: 'none')); //#23


  response.write("""

  	  </div>
 	</div>
	<div class="space space-south-east"  >
	  <div class="inner-space" >
        """); //#23

  response.write(Rsp.nnx(se, encode: 'none')); //#28


  response.write("""

  	  </div>
	</div>
"""); //#28

  return Rsp.nnf(centerWidget(new HttpConnect.chain(connect), centerId: "spaceCenter")).then((_) { //include#31

    response.write("""</div>"""); //#32

    return new Future.value();
  }); //end-of-include
}
