//Auto-generated by RSP Compiler
//Source: traceGpxViewer.rsp.html
part of trails;

/** Template, traceGpxViewer, for rendering the view. */
Future traceGpxViewer(HttpConnect connect, {traceAnalysisRenderer}) { //#3
  var _t0_, _cs_ = new List<HttpConnect>();
  HttpRequest request = connect.request;
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return new Future.value();

  if (traceAnalysisRenderer != null) { //if#3

    response.write("""      <div id="traceGpxViewer" style="overflow-x:hidden ; overflow-y:hidden ;  ">
        <iframe src="http://www.gpx-view.com/gpx.php?f="""); //#4

    response.write(Rsp.nnx(traceAnalysisRenderer.gpxUrl)); //#5


    response.write("""&mw=1000&m=GEOPORTAIL" name="GPX-View" scrolling="no" marginheight=0 marginwidth=0 frameborder=0 width=1500 height=450></iframe>
      </div>
"""); //#5
  } //if

  return new Future.value();
}
