//Auto-generated by RSP Compiler
//Source: traceStatisticsViewer.rsp.html
part of trails;

/** Template, traceStatisticsViewer, for rendering the view. */
Future traceStatisticsViewer(HttpConnect connect, {traceAnalysisRenderer}) { //#3
  var _t0_, _cs_ = new List<HttpConnect>();
  HttpRequest request = connect.request;
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return new Future.value();

  if (traceAnalysisRenderer != null) { //if#3

    response.write("""           <div>"""); //#4

    response.write(Rsp.nnx(traceAnalysisRenderer.lengthToRender)); //#4


    response.write(""" de distance</div>
           <div>"""); //#4

    response.write(Rsp.nnx(traceAnalysisRenderer.up)); //#5


    response.write(""" mètres de dénivelé positif</div>
           <div>"""); //#5

    response.write(Rsp.nnx(traceAnalysisRenderer.inclinationUp)); //#6


    response.write(""" % d'inclinaison moyenne en monté</div>
           <div>"""); //#6

    response.write(Rsp.nnx(traceAnalysisRenderer.difficulty)); //#7


    response.write(""" points de difficulté</div>
"""); //#7
  } //if

  return new Future.value();
}
