//Auto-generated by RSP Compiler
//Source: index.rsp.html
part of trails;

/** Template, index, for rendering the view. */
Future index(HttpConnect connect) { //#2
  var _t0_, _cs_ = new List<HttpConnect>();
  HttpRequest request = connect.request;
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return new Future.value();

  response.write("""<!DOCTYPE html>
<html>
 <head>
     <title>La Boussole</title>
"""); //#2

  return connect.include("/rsp/templates/assetsimports.html").then((_) { //include#6

    response.write("""  </head>
  <body>   
"""); //#7

    var _0 = new StringBuffer(); _cs_.add(connect); //var#10
    connect = new HttpConnect.stringBuffer(connect, _0); response = connect.response;

    return Rsp.nnf(loadingWidget(new HttpConnect.chain(connect), loadingId: "loadingNW", size: "50")).then((_) { //include#11

      response.write("""        <div id="disclaimerNW" class="gx-hidden" >
"""); //#12

      return Rsp.nnf(disclaimerTextFragment(new HttpConnect.chain(connect))).then((_) { //include#13

        response.write("""        </div>
        <div id="indexNW" class="gx-hidden"  >
"""); //#14

        return Rsp.nnf(indexTextFragment(new HttpConnect.chain(connect))).then((_) { //include#16

          response.write("""        </div>
        <div id="aboutNW" class="gx-hidden" >
"""); //#17

          return Rsp.nnf(aboutApplicationFragment(new HttpConnect.chain(connect))).then((_) { //include#19

            response.write("""        </div>        
"""); //#20

            connect = _cs_.removeLast(); response = connect.response;

            var _1 = new StringBuffer(); _cs_.add(connect); //var#22
            connect = new HttpConnect.stringBuffer(connect, _1); response = connect.response;

            return Rsp.nnf(loadingWidget(new HttpConnect.chain(connect), loadingId: "loadingNE", size: "50")).then((_) { //include#23

              response.write("""        <div id="aboutNE" class="gx-hidden" >
"""); //#24

              return Rsp.nnf(aboutDevFragment(new HttpConnect.chain(connect))).then((_) { //include#25

                response.write("""        </div>
"""); //#26

                connect = _cs_.removeLast(); response = connect.response;

                var _2 = new StringBuffer(); _cs_.add(connect); //var#28
                connect = new HttpConnect.stringBuffer(connect, _2); response = connect.response;

                return Rsp.nnf(loadingWidget(new HttpConnect.chain(connect), loadingId: "loadingSW", size: "50")).then((_) { //include#29

                  response.write("""        <div id="indexSW" class="gx-hidden"  >
"""); //#30

                  return Rsp.nnf(indexButtonsFragment(new HttpConnect.chain(connect))).then((_) { //include#31

                    response.write("""        </div>
        <div id="aboutSW" class="gx-hidden" >
"""); //#32

                    return Rsp.nnf(aboutFeedbacksFragment(new HttpConnect.chain(connect))).then((_) { //include#34

                      response.write("""        </div>        
"""); //#35

                      connect = _cs_.removeLast(); response = connect.response;

                      var _3 = new StringBuffer(); _cs_.add(connect); //var#37
                      connect = new HttpConnect.stringBuffer(connect, _3); response = connect.response;

                      return Rsp.nnf(loadingWidget(new HttpConnect.chain(connect), loadingId: "loadingSE", size: "50")).then((_) { //include#38

                        response.write("""        <div id="aboutSE" class="gx-hidden" >
"""); //#39

                        return Rsp.nnf(aboutAuthorFragment(new HttpConnect.chain(connect))).then((_) { //include#40

                          response.write("""        </div>        
"""); //#41

                          connect = _cs_.removeLast(); response = connect.response;

                          return Rsp.nnf(spaces(new HttpConnect.chain(connect), nw: _0.toString(), ne: _1.toString(), sw: _2.toString(), se: _3.toString())).then((_) { //include#9

                            return Rsp.nnf(sharedWidgets(new HttpConnect.chain(connect), sharedWidgetsId: "sharedWidgets")).then((_) { //include#44

                              response.write("""    
    <script type="application/dart" src="/client/pages/index.dart"></script>
    <script src="/packages/browser/dart.js"></script>
  </body>
</html>"""); //#45

                              return new Future.value();
                            }); //end-of-include
                          }); //end-of-include
                        }); //end-of-include
                      }); //end-of-include
                    }); //end-of-include
                  }); //end-of-include
                }); //end-of-include
              }); //end-of-include
            }); //end-of-include
          }); //end-of-include
        }); //end-of-include
      }); //end-of-include
    }); //end-of-include
  }); //end-of-include
}
