//Auto-generated by RSP Compiler
//Source: index.rsp.html
part of trails;

/** Template, index, for rendering the view. */
Future index(HttpConnect connect) { //#2
  var _t0_, _cs_ = new List<HttpConnect>();
  HttpRequest request = connect.request;
  HttpResponse response = connect.response;
  Rsp.init(connect, "text/html; charset=utf-8");

  response.write("""<!DOCTYPE html>

<html>
 <head>
	 <title>La Boussole</title>
"""); //#2

  return connect.include("/rsp/templates/assetsimports.html").then((_) { //include#7

    response.write("""  </head>
  <body>   
  
  <div class="spaces" >
    <div class="space space-north-west"  > &nbsp; </div>
    <div class="space space-north-east"  > &nbsp; </div>
    <div class="space space-south-west"  > &nbsp; </div>
    <div class="space space-south-east"  > &nbsp; </div>
"""); //#8

    return Rsp.nnf(center(new HttpConnect.chain(connect))).then((_) { //include#16

      return Rsp.nnf(menu(new HttpConnect.chain(connect))).then((_) { //include#17

        response.write("""  </div>

    <script type="application/dart" src="client/index.dart"></script>
    <script src="packages/browser/dart.js"></script>
  </body>
</html>
"""); //#18

        return Rsp.nnf();
      }); //end-of-include
    }); //end-of-include
  }); //end-of-include
}
