//Auto-generated by RSP Compiler
//Source: login.rsp.html
part of trails;

/** Template, login, for rendering the view. */
Future login(HttpConnect connect) { //#2
  var _t0_, _cs_ = new List<HttpConnect>();
  HttpRequest request = connect.request;
  HttpResponse response = connect.response;
  Rsp.init(connect, "text/html; charset=utf-8");

  response.write("""<!DOCTYPE html>

<html>
 <head>
	 <title>La Boussole - Connection</title>
"""); //#2

  return connect.include("/rsp/templates/assetsimports.html").then((_) { //include#7

    response.write("""  </head>
 
  <body>   
  
  <div class="spaces" >
    <div class="space space-north-west"  > 
    
        <h1>Connection</h1>
        
"""); //#8

    if (request.uri.queryParameters["retry"] != null) { //if#17

      response.write("""        <div class="text-warning">Mauvais login ou mot de passe.</div>
"""); //#18
    } //if

    response.write("""        <form role="form"  action="/s_login" method="post" accept-charset="UTF-8">
          <div class="form-group">
            <input name="s_username" type="text" class="form-control" id="login" placeholder="Login">
          </div>
          <div class="form-group">
            <input name="s_password" type="password" class="form-control" id="password" placeholder="Mot de passe">
          </div>        
          <button type="submit" class="btn btn-default">Se connecter</button>
        </form>

    </div>
    <div class="space space-north-east"  > &nbsp; </div>
    <div class="space space-south-west"  > &nbsp; </div>
    <div class="space space-south-east"  > &nbsp; </div>
"""); //#20

    return Rsp.nnf(center(new HttpConnect.chain(connect))).then((_) { //include#34

      return Rsp.nnf(menu(new HttpConnect.chain(connect))).then((_) { //include#35

        response.write("""  </div>


    <script type="application/dart" src="client/index.dart"></script>
    <script src="packages/browser/dart.js"></script>
  </body>
</html>
"""); //#36

        return Rsp.nnf();
      }); //end-of-include
    }); //end-of-include
  }); //end-of-include
}
