//Auto-generated by RSP Compiler
//Source: mock.rsp.html
part of trails;

/** Template, mock, for rendering the view. */
Future mock(HttpConnect connect) { //#2
  var _t0_, _cs_ = new List<HttpConnect>();
  HttpRequest request = connect.request;
  HttpResponse response = connect.response;
  Rsp.init(connect, "text/html; charset=utf-8");

  response.write("""<!DOCTYPE html>
<html>
 <head>
   <title>La Boussole - Maquette</title>
"""); //#2

  return connect.include("/rsp/templates/assetsimports.html").then((_) { //include#6

    response.write("""  </head>
  <body>   
"""); //#7

    var _0 = new StringBuffer(); _cs_.add(connect); //var#10
    connect = new HttpConnect.stringBuffer(connect, _0); response = connect.response;

    response.write("""        <h1>La montée du Moucherotte</h1>
        <h2>Le topo</h2>
        <p>Longer l'ancien téléski, puis monter droit au-dessus dans la trouée de la forêt (ancienne piste de ski: pente plus soutenue et vernes en train de repousser).
          A 1410m, l'ancienne piste part à gauche par une route qui contourne la montagne versant Grenoble (plat...). Cette route passe un semblant de défilé rocheux, puis traverse vers le S et monte en lacets vers le sommet (relais radio).
          Les derniers lacets peuvent être coupés.
          Les ruines de l'hôtel qui donnait autrefois du "caractère" au sommet ont été détruites.</p>
"""); //#11

    connect = _cs_.removeLast(); response = connect.response;

    var _1 = new StringBuffer(); _cs_.add(connect); //var#18
    connect = new HttpConnect.stringBuffer(connect, _1); response = connect.response;

    response.write("""         <div class="align-middle"><img style="margin-top: 80px" src="assets/img/mock_elevation.jpg"></img> </div>
"""); //#19

    connect = _cs_.removeLast(); response = connect.response;

    var _2 = new StringBuffer(); _cs_.add(connect); //var#21
    connect = new HttpConnect.stringBuffer(connect, _2); response = connect.response;

    response.write("""         <div class="align-middle"><img width="600px" src="assets/img/mock_map.jpg"></img> </div>
"""); //#22

    connect = _cs_.removeLast(); response = connect.response;

    var _3 = new StringBuffer(); _cs_.add(connect); //var#24
    connect = new HttpConnect.stringBuffer(connect, _3); response = connect.response;

    response.write("""         <div class="align-middle"><img  width="400px" src="assets/img/mock_picture.png"></img></div>
"""); //#25

    connect = _cs_.removeLast(); response = connect.response;

    return Rsp.nnf(spaces(new HttpConnect.chain(connect), nw: _0.toString(), ne: _1.toString(), sw: _2.toString(), se: _3.toString())).then((_) { //include#9

      response.write("""    <script type="application/dart" src="client/mock.dart"></script>
    <script src="packages/browser/dart.js"></script>
  </body>
</html>










"""); //#28

      return Rsp.nnf();
    }); //end-of-include
  }); //end-of-include
}
