//Auto-generated by RSP Compiler
//Source: traceAddFormView.rsp.html
part of trails;

/** Template, traceAddFormView, for rendering the view. */
Future traceAddFormView(HttpConnect connect, {traceFormRenderer}) { //#2
  var _t0_, _cs_ = new List<HttpConnect>();
  HttpRequest request = connect.request;
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return new Future.value();

  response.write("""<!DOCTYPE html>
<html>
 <head>
	 <title>La Boussole - Ajout d'une trace</title>
"""); //#2

  return connect.include("/rsp/templates/assetsimports.html").then((_) { //include#6

    response.write("""  </head>
  <body>   
"""); //#7

    var _0 = new StringBuffer(); _cs_.add(connect); //var#10
    connect = new HttpConnect.stringBuffer(connect, _0); response = connect.response;

    response.write("""        <h1>Ajout d'une trace gpx</h1>

        <form id="trace-add-form" role="form"  action="/trace" method="post" accept-charset="UTF-8" enctype="multipart/form-data" >
          <table  style="width: 100% ; ">
          <tr>
             <td style="width: 20%;" ></td>
             <td colspan="2" style="width: * ; text-align: center;"   >
                <div class="form-inputs" >
                    <input name="title" type="text" class="form-control" style="width: 80%" placeholder="Titre">
                </div>
             </td>
             <td style="width: 20%" ></td>
          </tr>
          <tr>
             <td  ></td>
             <td colspan="2" style="width: * ; text-align: center;"  >
                <div class="form-inputs">
                  <textarea name="description" class="form-control" style="width: 80%" rows="12" placeholder="Description du parcours" ></textarea>
                </div>              
             </td>
             <td  ></td>
          </tr>
          <tr>
             <td  ></td>
             <td style="width: 20%  ; " ></td>
             <td style="width: * ; text-align: left ;"  >
              <div class="form-inputs" >
                   <div>
"""); //#11

    for (var activity in traceFormRenderer.activities.keys) { //for#39

      response.write("""                        <div><input type="checkbox" name=\""""); //#40

      response.write(Rsp.nnx(activity)); //#40


      response.write(""""  style="vertical-align: middle;"  >&nbsp;&nbsp;<span style="vertical-align: middle;"  >"""); //#40

      response.write(Rsp.nnx(traceFormRenderer.activities[activity])); //#40


      response.write("""</span></div>
"""); //#40
    } //for

    response.write("""                   </div> 
              </div>             
             </td>
             <td  ></td>
          </tr>
          <tr>
             <td  ></td>
             <td colspan="2" style="width: * ; text-align: center;"  >
                <div class="form-inputs" >
                  <input name="gpxUploadedFile" type="file" title="Télécharger un fichier gpx" placeholder="Télécharger un fichier gpx" />
                </div>             
             </td>
             <td  ></td>
          </tr> 
          <tr>
             <td  ></td>
             <td colspan="2" style="width: * ; text-align: center;"  >
                <div class="form-inputs" >
                   <select  name="smoothing" >
                    <option value="no">Aucun lissage</option>
                    <option value="low">Lissage faible</option>
                    <option value="medium">Lissage moyen</option>
                    <option value="high">Lissage fort</option>
                  </select>
                </div>             
             </td>
             <td  ></td>
          </tr>          
          <tr>
             <td  ></td>
             <td colspan="2" style="width: * ; text-align: center;"  >
                <div class="form-inputs" >
                 <button type="submit"  class="btn btn-primary btn-add-trace loading-on-click">Ajouter cette trace</button>
                </div> 
             </td>
             <td  ></td>
          </tr>                              
          </table>
        </form>
"""); //#42

    connect = _cs_.removeLast(); response = connect.response;

    var _1 = new StringBuffer(); _cs_.add(connect); //var#82
    connect = new HttpConnect.stringBuffer(connect, _1); response = connect.response;

    response.write("""

"""); //#83

    connect = _cs_.removeLast(); response = connect.response;

    var _2 = new StringBuffer(); _cs_.add(connect); //var#85
    connect = new HttpConnect.stringBuffer(connect, _2); response = connect.response;

    response.write("""

"""); //#86

    connect = _cs_.removeLast(); response = connect.response;

    var _3 = new StringBuffer(); _cs_.add(connect); //var#88
    connect = new HttpConnect.stringBuffer(connect, _3); response = connect.response;

    response.write("""

"""); //#89

    connect = _cs_.removeLast(); response = connect.response;

    return Rsp.nnf(spaces(new HttpConnect.chain(connect), nw: _0.toString(), ne: _1.toString(), sw: _2.toString(), se: _3.toString())).then((_) { //include#9

      response.write("""    
"""); //#92

      return Rsp.nnf(sharedWidgets(new HttpConnect.chain(connect), sharedWidgetsId: "sharedWidgets")).then((_) { //include#93

        response.write("""    
    <script type="application/dart" src="/client/pages/traceAddForm.dart"></script>
    <script src="/packages/browser/dart.js"></script>
  </body>
</html>"""); //#94

        return new Future.value();
      }); //end-of-include
    }); //end-of-include
  }); //end-of-include
}
