//Auto-generated by RSP Compiler
//Source: traceFormatGpxView.rsp.html
part of trails;

/** Template, traceFormatGpxView, for rendering the view. */
Future traceFormatGpxView(HttpConnect connect, {trace}) { //#2
  var _t0_, _cs_ = new List<HttpConnect>();
  HttpRequest request = connect.request;
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return new Future.value();

  response.write("""<?xml version="1.0" encoding="UTF-8" ?>
<gpx version="1.1" creator="la-boussole" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.topografix.com/GPX/1/1" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">
    <trk>
        <name>la-boussole - """); //#2

  response.write(Rsp.nnx(trace.title)); //#5


  response.write("""</name>
        <trkseg>
"""); //#5

  for (var point in trace.points) { //for#7

    response.write("""            <trkpt lat=\""""); //#8

    response.write(Rsp.nnx(point.latitude)); //#8


    response.write("""" lon=\""""); //#8

    response.write(Rsp.nnx(point.longitude)); //#8


    response.write("""">
                <ele>"""); //#8

    response.write(Rsp.nnx(point.elevetion)); //#9


    response.write("""</ele>
            </trkpt>
"""); //#9
  } //for

  response.write("""        </trkseg>
    </trk>
</gpx>"""); //#12

  return new Future.value();
}
