//Auto-generated by RSP Compiler
//Source: traceView.rsp.html
part of trails;

/** Template, traceView, for rendering the view. */
Future traceView(HttpConnect connect, {traceRenderer}) { //#2
  var _t0_, _cs_ = new List<HttpConnect>();
  HttpRequest request = connect.request;
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return new Future.value();

  response.write("""<!DOCTYPE html>
<html>
 <head>
   <title>La Boussole - """); //#2

  response.write(Rsp.nnx(traceRenderer.trace.title)); //#5


  response.write("""</title>
"""); //#5

  return connect.include("/rsp/templates/assetsimports.html").then((_) { //include#6

    response.write("""  </head>
  <body>   
"""); //#7

    var _0 = new StringBuffer(); _cs_.add(connect); //var#10
    connect = new HttpConnect.stringBuffer(connect, _0); response = connect.response;

    return Rsp.nnf(traceProfileViewer(new HttpConnect.chain(connect), traceAnalysisRenderer: traceRenderer.traceAnalysisRenderer)).then((_) { //include#11

      connect = _cs_.removeLast(); response = connect.response;

      var _1 = new StringBuffer(); _cs_.add(connect); //var#13
      connect = new HttpConnect.stringBuffer(connect, _1); response = connect.response;

      response.write("""               <h1 class="data-key" data-key=\""""); //#14

      response.write(Rsp.nnx(traceRenderer.trace.key)); //#14


      response.write(""""   >"""); //#14

      response.write(Rsp.nnx(traceRenderer.trace.title)); //#14


      response.write("""</h1>
               <div class="trace-activities important-text" >
                 """); //#14

      response.write(Rsp.nnx(traceRenderer.activities)); //#16


      response.write("""

               </div>
                         
               <div class="trace-description" >
                 """); //#16

      response.write(Rsp.nnx(traceRenderer.description, encode: 'none')); //#20


      response.write("""

               </div>
               <div class="trace-creator note-text" >
                 <a rel="license" target="_blank" href="http://creativecommons.org/licenses/by-nc-nd/3.0/fr/"><img alt="Licence Creative Commons" style="border-width:0" src="http://i.creativecommons.org/l/by-nc-nd/3.0/fr/88x31.png" /></a>&nbsp;trace ajoutée par """); //#20

      response.write(Rsp.nnx(traceRenderer.trace.creator)); //#23


      response.write("""

               </div>
               <div class="trace-lastupdate note-text" >
                 mise à jour le """); //#23

      response.write(Rsp.nnx(traceRenderer.lastUpdateDate)); //#26


      response.write("""

               </div>
               
               
"""); //#26

      connect = _cs_.removeLast(); response = connect.response;

      var _2 = new StringBuffer(); _cs_.add(connect); //var#31
      connect = new HttpConnect.stringBuffer(connect, _2); response = connect.response;

      return Rsp.nnf(traceGpxViewer(new HttpConnect.chain(connect), traceRenderer: traceRenderer)).then((_) { //include#32

        connect = _cs_.removeLast(); response = connect.response;

        var _3 = new StringBuffer(); _cs_.add(connect); //var#34
        connect = new HttpConnect.stringBuffer(connect, _3); response = connect.response;

        return Rsp.nnf(traceStatisticsViewer(new HttpConnect.chain(connect), traceAnalysisRenderer: traceRenderer.traceAnalysisRenderer)).then((_) { //include#35

          connect = _cs_.removeLast(); response = connect.response;

          return Rsp.nnf(spaces(new HttpConnect.chain(connect), nw: _0.toString(), ne: _1.toString(), sw: _2.toString(), se: _3.toString())).then((_) { //include#9

            response.write("""    
    <div class="space-contextual-menu"  >
        <ul role="menu" class="dropdown-menu"  id="contextual-menu">
          <li role="presentation" class="dropdown-header">Trace gps</li>
          <li role="presentation"><a href=\""""); //#38

            response.write(Rsp.nnx(traceRenderer.gpxUrl)); //#42


            response.write("""" tabindex="-1" role="menuitem">Fichier gpx</a></li>
"""); //#42

            if (currentUser(request.session) != null && ( currentUser(request.session).login == traceRenderer.trace.creator || currentUser(request.session).admin   )) { //if#43

              response.write("""            <li role="presentation"><a class="trace-delete-menu gx-as-link"  tabindex="-1" role="menuitem">Supprimer</a></li>
"""); //#44
            } //if

            response.write("""       </ul>
    </div>
    
"""); //#46

            return Rsp.nnf(confirmWidget(new HttpConnect.chain(connect), confirmId: "deleteConfirmModal", confirmTitle: "Confirmation", confirmText: "Je confirme la suppression définitive de la trace ${Rsp.nns(traceRenderer.trace.title)}")).then((_) { //include#49

              return Rsp.nnf(sharedWidgets(new HttpConnect.chain(connect), sharedWidgetsId: "sharedWidgets")).then((_) { //include#50

                response.write("""    
    <script type="application/dart" src="/client/pages/traceAnalysis.dart"></script>
    <script src="/packages/browser/dart.js"></script>
    <script src="/packages/browser/interop.js"></script>
  </body>
</html>
"""); //#51

                return new Future.value();
              }); //end-of-include
            }); //end-of-include
          }); //end-of-include
        }); //end-of-include
      }); //end-of-include
    }); //end-of-include
  }); //end-of-include
}
