//Auto-generated by RSP Compiler
//Source: traceSearchView.rsp.html
part of trails;

/** Template, traceSearchView, for rendering the view. */
Future traceSearchView(HttpConnect connect, {traceLigthRenderers}) { //#2
  var _t0_, _cs_ = new List<HttpConnect>();
  HttpRequest request = connect.request;
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return new Future.value();

  response.write("""<!DOCTYPE html>
<html>
 <head>
     <title>La Boussole - Rechercher une trace gps</title>
"""); //#2

  return connect.include("/rsp/templates/assetsimports.html").then((_) { //include#6

    response.write("""  </head>
  <body>   
"""); //#7

    var _0 = new StringBuffer(); _cs_.add(connect); //var#10
    connect = new HttpConnect.stringBuffer(connect, _0); response = connect.response;

    response.write("""

        <h1>Rechercher une trace gps</h1>
        <div class="text-warning  form-error-message" >Actuellement en construction : la possibilité de rechercher par auteur, difficulté, localisation...</div>
"""); //#11

    connect = _cs_.removeLast(); response = connect.response;

    var _1 = new StringBuffer(); _cs_.add(connect); //var#15
    connect = new HttpConnect.stringBuffer(connect, _1); response = connect.response;

    response.write("""      
        <table class="table table-striped" style="margin-top: 40px">  
          <thead>  
            <tr>  
              <th>Auteur</th>  
              <th>Trace</th>  
              <th>Activités</th>  
              <th>Distance</th>  
              <th>Dénivelé</th>
              <th>Sommet</th>
              <th>Pente</th>
              <th>Difficulté</th>
            </tr>  
          </thead>  
          <tbody>  
          
"""); //#16

    for (var traceLigthRenderer in traceLigthRenderers) { //for#32

      response.write("""              <tr>  
                  <td>"""); //#33

      response.write(Rsp.nnx(traceLigthRenderer.trace.creator)); //#34


      response.write("""</td>  
                  <td><a href="/trace/"""); //#34

      response.write(Rsp.nnx(traceLigthRenderer.trace.key)); //#35


      response.write(""""  target="_blank">"""); //#35

      response.write(Rsp.nnx(traceLigthRenderer.trace.title)); //#35


      response.write("""</a> </td>  
                  <td>"""); //#35

      response.write(Rsp.nnx(traceLigthRenderer.activities)); //#36


      response.write("""</td>
                  <td>"""); //#36

      response.write(Rsp.nnx((traceLigthRenderer.trace.length/1000).round())); //#37


      response.write(""" km</td>  
                  <td>"""); //#37

      response.write(Rsp.nnx(traceLigthRenderer.trace.up)); //#38


      response.write(""" m</td>
                  <td>"""); //#38

      response.write(Rsp.nnx(traceLigthRenderer.trace.upperPointElevetion.round())); //#39


      response.write(""" m</td>
                  <td>"""); //#39

      response.write(Rsp.nnx(traceLigthRenderer.trace.inclinationUp)); //#40


      response.write(""" %</td>
                  <td>"""); //#40

      response.write(Rsp.nnx(traceLigthRenderer.trace.difficulty)); //#41


      response.write(""" pt</td>
              </tr>  
"""); //#41
    } //for

    response.write("""    
          </tbody>  
        </table>
        
"""); //#44

    connect = _cs_.removeLast(); response = connect.response;

    var _2 = new StringBuffer(); _cs_.add(connect); //var#49
    connect = new HttpConnect.stringBuffer(connect, _2); response = connect.response;

    connect = _cs_.removeLast(); response = connect.response;

    var _3 = new StringBuffer(); _cs_.add(connect); //var#50
    connect = new HttpConnect.stringBuffer(connect, _3); response = connect.response;

    response.write("""               <div class="text-warning  form-error-message" >Actuellement en construction : localisation sur une carte des traces gps</div>
"""); //#51

    connect = _cs_.removeLast(); response = connect.response;

    return Rsp.nnf(spaces(new HttpConnect.chain(connect), nw: _0.toString(), ne: _1.toString(), sw: _2.toString(), se: _3.toString())).then((_) { //include#9

      response.write("""    
    
    
    <script type="application/dart" src="/client/traceSearch.dart"></script>
    <script src="/packages/browser/dart.js"></script>
  </body>
</html>
"""); //#54

      return new Future.value();
    }); //end-of-include
  }); //end-of-include
}
