//Auto-generated by RSP Compiler
//Source: commentEditorWidget.rsp.html
part of trails;

/** Template, commentEditorWidget, for rendering the view. */
Future commentEditorWidget(HttpConnect connect, {commentEditorId}) { //#2
  var _t0_, _cs_ = new List<HttpConnect>();
  HttpRequest request = connect.request;
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return new Future.value();

  response.write("""

    <div id=\""""); //#2

  response.write(Rsp.nnx(commentEditorId)); //#3


  response.write("""" class="modal fade gx-hidden" tabindex="-1" role="dialog" style="z-index: 0">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h3 id=\""""); //#3

  response.write(Rsp.nnx(commentEditorId)); //#7


  response.write("""-header"  >Commentaire</h3>
          </div>
          <div class="modal-body">
              <div class="form-group">
                  <textarea  id=\""""); //#7

  response.write(Rsp.nnx(commentEditorId)); //#11


  response.write("""-content" class="form-control" style="width: 90%" rows="5" placeholder="Commentaire" ></textarea>
              </div>        
          </div>
          <div class="modal-footer">
              <div id=\""""); //#11

  response.write(Rsp.nnx(commentEditorId)); //#15


  response.write("""-error-message" class="text-warning" ></div>
              <button id=\""""); //#15

  response.write(Rsp.nnx(commentEditorId)); //#16


  response.write("""-btn-delete" type="submit" class="btn btn-warning">Supprimer</button>
              <button id=\""""); //#16

  response.write(Rsp.nnx(commentEditorId)); //#17


  response.write("""-btn-submit" type="submit" class="btn btn-primary">Ajouter</button>
              <button id=\""""); //#17

  response.write(Rsp.nnx(commentEditorId)); //#18


  response.write("""-btn-cancel" class="btn btn-default">Annuler</button>
          </div>
        </div>
      </div>
    </div>         
"""); //#18

  return new Future.value();
}
