//Auto-generated by RSP Compiler
//Source: confirmWidget.rsp.html
part of trails;

/** Template, confirmWidget, for rendering the view. */
Future confirmWidget(HttpConnect connect, {confirmId,confirmTitle,confirmText}) { //#2
  var _t0_, _cs_ = new List<HttpConnect>();
  HttpRequest request = connect.request;
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return new Future.value();

  response.write("""

    <div id=\""""); //#2

  response.write(Rsp.nnx(confirmId)); //#3


  response.write("""" class="modal fade" tabindex="-1" role="dialog">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h3 id=\""""); //#3

  response.write(Rsp.nnx(confirmId)); //#7


  response.write("""-title" >"""); //#7

  response.write(Rsp.nnx(confirmTitle)); //#7


  response.write("""</h3>
          </div>
          <div class="modal-body">
            <p id=\""""); //#7

  response.write(Rsp.nnx(confirmId)); //#10


  response.write("""-text" >"""); //#10

  response.write(Rsp.nnx(confirmText)); //#10


  response.write("""</p>
          </div>
          <div class="modal-footer">
            <button id=\""""); //#10

  response.write(Rsp.nnx(confirmId)); //#13


  response.write("""-btn-ok" class="btn btn-primary">OK</button>
            <button id=\""""); //#13

  response.write(Rsp.nnx(confirmId)); //#14


  response.write("""-btn-cancel" class="btn btn-default">Annuler</button>
          </div>
        </div>
      </div>
    </div> """); //#14

  return new Future.value();
}
