//Auto-generated by RSP Compiler
//Source: connectedUserWidget.rsp.html
part of trails;

/** Template, connectedUserWidget, for rendering the view. */
Future connectedUserWidget(HttpConnect connect) { //#2
  var _t0_, _cs_ = new List<HttpConnect>();
  HttpRequest request = connect.request;
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return new Future.value();

  response.write("""  <div class="gx-hidden" """); //#2

  if (currentUser(request.session) != null) { //if#2

    response.write("""data-connected-user-login=\""""); //#2

    response.write(Rsp.nnx(currentUser(request.session).login)); //#2


    response.write("""" data-connected-user-login=\""""); //#2

    response.write(Rsp.nnx(currentUser(request.session).admin)); //#2


    response.write("""" """); //#2
  } //if

  response.write("""  ></div>
"""); //#2

  return new Future.value();
}
