//Auto-generated by RSP Compiler
//Source: headerWidget.rsp.html
part of trails;

/** Template, headerWidget, for rendering the view. */
Future headerWidget(HttpConnect connect, {headerId}) { //#2
  var _t0_, _cs_ = new List<HttpConnect>();
  HttpRequest request = connect.request;
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return new Future.value();

  response.write("""<div id=\""""); //#2

  response.write(Rsp.nnx(headerId)); //#2


  response.write(""""   >
   <h1 id=\""""); //#2

  response.write(Rsp.nnx(headerId)); //#3


  response.write("""-title"  ></h1>
"""); //#3

  return Rsp.nnf(connectedUserWidget(new HttpConnect.chain(connect))).then((_) { //include#4

    response.write("""


   <div id=\""""); //#5

    response.write(Rsp.nnx(headerId)); //#7


    response.write("""-left">

     <span id=\""""); //#7

    response.write(Rsp.nnx(headerId)); //#9


    response.write("""-menu" class='gx-as-link' >
        <a title="Actions possibles" ><img id=\""""); //#9

    response.write(Rsp.nnx(headerId)); //#10


    response.write("""-menu-img" src='/assets/img/menu.png '  /></a>
     </span>
     <span id=\""""); //#10

    response.write(Rsp.nnx(headerId)); //#12


    response.write("""-search" class='gx-as-link' >
        <a title="Rechercher" ><img id=\""""); //#12

    response.write(Rsp.nnx(headerId)); //#13


    response.write("""-search-img" src='/assets/img/search.png '  /></a>
     </span>     
     <span id=\""""); //#13

    response.write(Rsp.nnx(headerId)); //#15


    response.write("""-feedback" class='gx-as-link """); //#15

    response.write(Rsp.nnx(currentUser(request.session) == null ? "gx-hidden" : "")); //#15


    response.write("""' >
        <a title="Retour utilisateur" ><img id=\""""); //#15

    response.write(Rsp.nnx(headerId)); //#16


    response.write("""-feedback-img" src='/assets/img/megaphone.png '  /></a>
     </span>        
   </div>

   <div id=\""""); //#16

    response.write(Rsp.nnx(headerId)); //#20


    response.write("""-right">
     <span id=\""""); //#20

    response.write(Rsp.nnx(headerId)); //#21


    response.write("""-register" class='gx-as-link """); //#21

    response.write(Rsp.nnx(currentUser(request.session) != null ? "gx-hidden" : "")); //#21


    response.write("""' >
        <a title="S'enregister" ><img  alt="S'enregister" src='/assets/img/register.png'  /></a>
     </span>     
     <span id=\""""); //#21

    response.write(Rsp.nnx(headerId)); //#24


    response.write("""-login" class='gx-as-link """); //#24

    response.write(Rsp.nnx(currentUser(request.session) != null ? "gx-hidden" : "")); //#24


    response.write("""' >
        <a title="Se connecter" ><img  src='/assets/img/login.png '  /></a>
     </span>
     <span id=\""""); //#24

    response.write(Rsp.nnx(headerId)); //#27


    response.write("""-logout" class='gx-as-link """); //#27

    response.write(Rsp.nnx(currentUser(request.session) == null ? "gx-hidden" : "")); //#27


    response.write("""' >
        <a title="Se déconnecter" ><img  src='/assets/img/logout.png '  /></a>
     </span>
     <span id=\""""); //#27

    response.write(Rsp.nnx(headerId)); //#30


    response.write("""-user" class='gx-as-link """); //#30

    response.write(Rsp.nnx(currentUser(request.session) != null &&  ! currentUser(request.session).admin  ?  "" : "gx-hidden")); //#30


    response.write("""' >
        <a title='Utilisateur """); //#30

    response.write(Rsp.nnx(currentUser(request.session) != null  ?  currentUser(request.session).login : "")); //#31


    response.write(""" (en construction)' ><img  src='/assets/img/user.png '  /></a>
     </span>
     <span id=\""""); //#31

    response.write(Rsp.nnx(headerId)); //#33


    response.write("""-admin" class='gx-as-link """); //#33

    response.write(Rsp.nnx(currentUser(request.session) != null &&   currentUser(request.session).admin  ?  "" : "gx-hidden")); //#33


    response.write("""' >
        <a title='Admin """); //#33

    response.write(Rsp.nnx(currentUser(request.session) != null  ?  currentUser(request.session).login : "")); //#34


    response.write(""" (en construction) ' ><img  src='/assets/img/admin.png '  /></a>
     </span>     
     <span id=\""""); //#34

    response.write(Rsp.nnx(headerId)); //#36


    response.write("""-previous" class='gx-as-link' >
        <a title="Page précedente" ><img id=\""""); //#36

    response.write(Rsp.nnx(headerId)); //#37


    response.write("""-back-img" src='/assets/img/back.png' style="width: 32px" /></a>
     </span>     
     <span id=\""""); //#37

    response.write(Rsp.nnx(headerId)); //#39


    response.write("""-pages" class='gx-as-link'  >
        <a title="Accès aux pages" ><img  src='/assets/img/pages.png'  /></a>
     </span>
     <span id=\""""); //#39

    response.write(Rsp.nnx(headerId)); //#42


    response.write("""-next" class='gx-as-link' >
        <a title="Page suivante" ><img id=\""""); //#42

    response.write(Rsp.nnx(headerId)); //#43


    response.write("""-next-img" src='/assets/img/next.png' style="width: 32px"  /></a>
     </span>       
   </div>

     <span id=\""""); //#43

    response.write(Rsp.nnx(headerId)); //#47


    response.write("""-close" class='gx-as-link' style="position:absolute; z-index: 500 ; right: 3px; top: 43px;" >
        <a title="Fermer la page courante" ><img  src='/assets/img/close.png'  /></a>
     </span>
"""); //#47

    return Rsp.nnf(menuWidget(new HttpConnect.chain(connect), menuId: "menu")).then((_) { //include#50

      return Rsp.nnf(menuWidget(new HttpConnect.chain(connect), menuId: "pageLinks")).then((_) { //include#51

        response.write("""</div>


"""); //#52

        return new Future.value();
      }); //end-of-include
    }); //end-of-include
  }); //end-of-include
}
