//Auto-generated by RSP Compiler
//Source: headerWidget.rsp.html
part of trails;

/** Template, headerWidget, for rendering the view. */
Future headerWidget(HttpConnect connect, {headerId}) { //#2
  var _t0_, _cs_ = new List<HttpConnect>();
  HttpRequest request = connect.request;
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return new Future.value();

  response.write("""<div id=\""""); //#2

  response.write(Rsp.nnx(headerId)); //#2


  response.write(""""   >
   <h1 id=\""""); //#2

  response.write(Rsp.nnx(headerId)); //#3


  response.write("""-title"  ></h1>
"""); //#3

  return Rsp.nnf(connectedUserWidget(new HttpConnect.chain(connect))).then((_) { //include#4

    response.write("""</div>
"""); //#5

    return new Future.value();
  }); //end-of-include
}
