//Auto-generated by RSP Compiler
//Source: loadingWidget.rsp.html
part of trails;

/** Template, loadingWidget, for rendering the view. */
Future loadingWidget(HttpConnect connect, {loadingId,size}) { //#2
  var _t0_, _cs_ = new List<HttpConnect>();
  HttpRequest request = connect.request;
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return new Future.value();

  response.write("""<div id=\""""); //#2

  response.write(Rsp.nnx(loadingId)); //#2


  response.write("""">
    <img class="gx-hidden" height=\""""); //#2

  response.write(Rsp.nnx(size)); //#3


  response.write("""px" width=\""""); //#3

  response.write(Rsp.nnx(size)); //#3


  response.write("""px" src="/assets/img/spinner.gif"></img>
</div>
"""); //#3

  return new Future.value();
}
