//Auto-generated by RSP Compiler
//Source: logoutWidget.rsp.html
part of trails;

/** Template, logoutWidget, for rendering the view. */
Future logoutWidget(HttpConnect connect, {logoutId}) { //#2
  var _t0_, _cs_ = new List<HttpConnect>();
  HttpRequest request = connect.request;
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return new Future.value();

  response.write("""    <div id=\""""); //#2

  response.write(Rsp.nnx(logoutId)); //#2


  response.write("""" class="gx-hidden" ></div>"""); //#2

  return new Future.value();
}
