//Auto-generated by RSP Compiler
//Source: menuWidget.rsp.html
part of trails;

/** Template, menuWidget, for rendering the view. */
Future menuWidget(HttpConnect connect, {menuId}) { //#2
  var _t0_, _cs_ = new List<HttpConnect>();
  HttpRequest request = connect.request;
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return new Future.value();

  response.write("""<div id=\""""); //#2

  response.write(Rsp.nnx(menuId)); //#2


  response.write("""" >
      <ul role="menu" class="dropdown-menu"  >
      </ul>
</div>    
"""); //#2

  return new Future.value();
}
