//Auto-generated by RSP Compiler
//Source: profileWidget.rsp.html
part of trails;

/** Template, profileWidget, for rendering the view. */
Future profileWidget(HttpConnect connect, {profileId}) { //#2
  var _t0_, _cs_ = new List<HttpConnect>();
  HttpRequest request = connect.request;
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return new Future.value();

  response.write("""<div id=\""""); //#2

  response.write(Rsp.nnx(profileId)); //#2


  response.write("""" class="gx-no-scroll gx-absolute-position" ></div>"""); //#2

  return new Future.value();
}
