//Auto-generated by RSP Compiler
//Source: watchPointEditorWidget.rsp.html
part of trails;

/** Template, watchPointEditorWidget, for rendering the view. */
Future watchPointEditorWidget(HttpConnect connect, {watchPointEditorId}) { //#2
  var _t0_, _cs_ = new List<HttpConnect>();
  HttpRequest request = connect.request;
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return new Future.value();

  response.write("""

    <div id=\""""); //#2

  response.write(Rsp.nnx(watchPointEditorId)); //#3


  response.write("""" class="modal fade gx-hidden" tabindex="-1" role="dialog">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h3>Ajout d'un marqueur</h3>
          </div>
          <div class="modal-body">
              <div class="form-group">
                <input  id=\""""); //#3

  response.write(Rsp.nnx(watchPointEditorId)); //#11


  response.write("""-name" type="text" class="form-control"  placeholder="Nom">
              </div>
              <div class="form-group">
                  <textarea  id=\""""); //#11

  response.write(Rsp.nnx(watchPointEditorId)); //#14


  response.write("""-description" class="form-control" style="width: 80%" rows="5" placeholder="Description" ></textarea>
              </div>        
              <div class="form-group">Latitude : <span id=\""""); //#14

  response.write(Rsp.nnx(watchPointEditorId)); //#16


  response.write("""-latitude" ></span></div>     
              <div class="form-group">Longitude : <span id=\""""); //#16

  response.write(Rsp.nnx(watchPointEditorId)); //#17


  response.write("""-longitude" ></span></div>     
          </div>
          <div class="modal-footer">
              <div id=\""""); //#17

  response.write(Rsp.nnx(watchPointEditorId)); //#20


  response.write("""-error-message" class="text-warning" ></div>
              <button id=\""""); //#20

  response.write(Rsp.nnx(watchPointEditorId)); //#21


  response.write("""-btn-submit" type="submit" class="btn btn-primary btn-submit-register">Ajouter</button>
              <button id=\""""); //#21

  response.write(Rsp.nnx(watchPointEditorId)); //#22


  response.write("""-btn-cancel" class="btn btn-default">Annuler</button>
          </div>
        </div>
      </div>
    </div>         
"""); //#22

  return new Future.value();
}
