//Auto-generated by RSP Compiler
//Source: watchPointEditorWidget.rsp.html
part of trails;

/** Template, watchPointEditorWidget, for rendering the view. */
Future watchPointEditorWidget(HttpConnect connect, {watchPointEditorId}) { //#2
  var _t0_, _cs_ = new List<HttpConnect>();
  HttpRequest request = connect.request;
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return new Future.value();

  response.write("""

    <div id=\""""); //#2

  response.write(Rsp.nnx(watchPointEditorId)); //#3


  response.write("""" class="modal fade gx-hidden" tabindex="-1" role="dialog" style="z-index: 0">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h3>Ajout d'un marqueur</h3>
          </div>
          <div class="modal-body">
              <div class="form-group">
                <select id=\""""); //#3

  response.write(Rsp.nnx(watchPointEditorId)); //#11


  response.write("""-type" class="form-control">
                    <option value="step">étape</option>
                    <option value="camp">bivouac</option>
                    <option value="water">point d'eau</option>
                </select>
                
                <input  id=\""""); //#11

  response.write(Rsp.nnx(watchPointEditorId)); //#17


  response.write("""-name" type="text" class="form-control"  placeholder="Nom">
              </div>
              <div class="form-group">
                  <textarea  id=\""""); //#17

  response.write(Rsp.nnx(watchPointEditorId)); //#20


  response.write("""-description" class="form-control" style="width: 90%" rows="5" placeholder="Description" ></textarea>
              </div>        
              <div class="form-group">Latitude : <span id=\""""); //#20

  response.write(Rsp.nnx(watchPointEditorId)); //#22


  response.write("""-latitude" ></span></div>     
              <div class="form-group">Longitude : <span id=\""""); //#22

  response.write(Rsp.nnx(watchPointEditorId)); //#23


  response.write("""-longitude" ></span></div>     
          </div>
          <div class="modal-footer">
              <div id=\""""); //#23

  response.write(Rsp.nnx(watchPointEditorId)); //#26


  response.write("""-error-message" class="text-warning" ></div>
              <button id=\""""); //#26

  response.write(Rsp.nnx(watchPointEditorId)); //#27


  response.write("""-btn-delete" type="submit" class="btn btn-warning">Supprimer</button>
              <button id=\""""); //#27

  response.write(Rsp.nnx(watchPointEditorId)); //#28


  response.write("""-btn-submit" type="submit" class="btn btn-primary">Ajouter</button>
              <button id=\""""); //#28

  response.write(Rsp.nnx(watchPointEditorId)); //#29


  response.write("""-btn-cancel" class="btn btn-default">Annuler</button>
          </div>
        </div>
      </div>
    </div>         
"""); //#29

  return new Future.value();
}
